import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Family Trivia",
  description: "Terms of Service for Family Trivia app",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-8">
          <Link href="/" className="text-primary hover:underline mb-4 inline-block">
            &larr; Back to Home
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            Terms of Service
          </h1>
          <p className="text-gray-600 dark:text-gray-400">Last updated: November 20, 2025</p>
        </div>

        <div className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-gray-800 dark:text-gray-200">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing or using the Family Trivia mobile application (&quot;App&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the App.
            </p>
            <p className="mb-4">
              <strong>You must be at least 13 years old to use this App.</strong> By using the App, you represent and warrant that you are at least 13 years of age. If you are under 13, you may not use the App.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">2. Description of Service</h2>
            <p className="mb-4">
              Family Trivia is a trivia game application that uses artificial intelligence to generate questions and content. The service is provided &quot;as is&quot; for entertainment and educational purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">3. AI-Generated Content Disclaimer</h2>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3.1 No Guarantee of Accuracy</h3>
            <p className="mb-4">
              The App uses artificial intelligence to generate trivia questions and content. <strong>WE DO NOT GUARANTEE THE ACCURACY, RELIABILITY, COMPLETENESS, OR APPROPRIATENESS OF ANY AI-GENERATED CONTENT.</strong> Questions and answers may contain errors, inaccuracies, or outdated information.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3.2 Inappropriate Content</h3>
            <p className="mb-4">
              Despite our content filtering efforts, AI-generated content may occasionally produce inappropriate, offensive, or objectionable material. <strong>WE ARE NOT RESPONSIBLE FOR ANY INAPPROPRIATE, OFFENSIVE, OR HARMFUL CONTENT GENERATED BY THE AI SYSTEM.</strong> Users are encouraged to report such content immediately.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3.3 User Discretion</h3>
            <p className="mb-4">
              Users should exercise their own judgment and discretion when using AI-generated content. Parents and guardians should supervise children&apos;s use of the App and are responsible for determining whether content is appropriate for their children.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">4. User Responsibilities</h2>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4.1 Acceptable Use</h3>
            <p className="mb-4">You agree to use the App only for lawful purposes and in accordance with these Terms. You agree NOT to:</p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Use the App in any way that violates applicable laws or regulations</li>
              <li>Attempt to reverse engineer, decompile, or hack the App</li>
              <li>Use the App to harass, abuse, or harm others</li>
              <li>Share or distribute inappropriate content with other users</li>
              <li>Attempt to manipulate or exploit AI systems</li>
              <li>Create multiple accounts to abuse the service</li>
              <li>Use automated systems or bots to interact with the App</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4.2 Account Security</h3>
            <p className="mb-4">
              You are responsible for maintaining the security of your account and for all activities that occur under your account. Notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">5. Limitation of Liability</h2>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5.1 No Liability for Content</h3>
            <p className="mb-4"><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE ARE NOT LIABLE FOR ANY DAMAGES, LOSSES, OR HARM ARISING FROM:</strong></p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Inaccurate, misleading, or erroneous AI-generated content</li>
              <li>Inappropriate, offensive, or harmful content generated by the AI</li>
              <li>User reliance on AI-generated information</li>
              <li>Any decisions made based on content in the App</li>
              <li>Emotional distress or offense caused by content</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5.2 General Disclaimer</h3>
            <p className="mb-4"><strong>THE APP IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:</strong></p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Warranties of merchantability or fitness for a particular purpose</li>
              <li>Warranties regarding accuracy, reliability, or availability</li>
              <li>Warranties that the service will be uninterrupted or error-free</li>
              <li>Warranties that defects will be corrected</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5.3 Maximum Liability</h3>
            <p className="mb-4">
              <strong>IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, OR GOODWILL ARISING FROM YOUR USE OF THE APP.</strong>
            </p>
            <p className="mb-4">
              To the extent permitted by law, our total liability to you for all claims arising from or related to the App shall not exceed the amount you paid to us in the past twelve months, or $100, whichever is less.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">6. Indemnification</h2>
            <p className="mb-4">
              You agree to indemnify, defend, and hold harmless Family Trivia, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Your use or misuse of the App</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any rights of another person or entity</li>
              <li>Any content you submit or share through the App</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">7. Content Moderation</h2>
            <p className="mb-4">
              We reserve the right, but have no obligation, to monitor, filter, or remove content. We may suspend or terminate accounts that violate these Terms or generate/share inappropriate content.
            </p>
            <p className="mb-4">
              Users can report inappropriate content through the in-app reporting feature. We will review reports and take appropriate action, but we make no guarantees about response times or outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">8. Intellectual Property</h2>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">8.1 Our Rights</h3>
            <p className="mb-4">
              The App, including its design, features, and original content (excluding AI-generated content), is owned by us and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our permission.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">8.2 AI-Generated Content</h3>
            <p className="mb-4">
              AI-generated content is provided for your personal, non-commercial use within the App. We make no claims of ownership or control over AI-generated content, and you use such content at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">9. Third-Party Services</h2>
            <p className="mb-4">
              The App uses third-party AI services and other technologies. We are not responsible for the performance, availability, or policies of these third-party services. Your use of third-party services may be subject to their own terms and conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">10. Termination</h2>
            <p className="mb-4">
              We reserve the right to suspend or terminate your access to the App at any time, with or without cause or notice, including for violations of these Terms. You may also terminate your account at any time by contacting us or deleting the App.
            </p>
            <p className="mb-4">
              Upon termination, your right to use the App will immediately cease. Sections of these Terms that by their nature should survive termination will survive.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">11. Age Requirement</h2>
            <p className="mb-4">
              The App is intended for users aged 13 and older. If you are under 13, you are not permitted to use the App. We reserve the right to terminate accounts of users we discover are under 13 years of age.
            </p>
            <p className="mb-4">
              Parents and guardians of users aged 13-17 are encouraged to supervise their children&apos;s use of the App and determine whether content is appropriate.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">12. Changes to Terms</h2>
            <p className="mb-4">
              We may modify these Terms at any time. We will notify you of significant changes through the App or via email. Your continued use of the App after changes constitutes acceptance of the modified Terms. If you do not agree to the changes, you must stop using the App.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">13. Governing Law and Disputes</h2>
            <p className="mb-4">
              These Terms shall be governed by and construed in accordance with the laws of the United States and the state in which we are incorporated, without regard to conflict of law principles.
            </p>
            <p className="mb-4">
              Any disputes arising from these Terms or your use of the App shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association, except where prohibited by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">14. Severability</h2>
            <p className="mb-4">
              If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">15. Entire Agreement</h2>
            <p className="mb-4">
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and Family Trivia regarding your use of the App and supersede all prior agreements and understandings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">16. Contact Information</h2>
            <p className="mb-4">If you have questions about these Terms, please contact us at:</p>
            <p className="mb-4">
              Email: <a href="mailto:legal@familytrivia.app" className="text-primary hover:underline">legal@familytrivia.app</a>
            </p>
          </section>

          <div className="mt-8 p-6 bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 rounded">
            <p className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">Important Notice:</p>
            <p className="text-yellow-700 dark:text-yellow-300">
              By using Family Trivia, you acknowledge that AI-generated content may contain errors or inappropriate material, and you agree that we are not liable for any such content or any consequences arising from your use of the App.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
